version: "3"
services:
  monapp:
    image: colewski/test-docker
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"

  mysql:
    image: mysql
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment: 
      MYSQL_ROOT_PASSWORD: root
    ports: 
      - "3306:3306"
    volumes:
      - ./mysql-volume:/var/lib/mysql
